USE [Cam_Do_Database]
GO

/****** Object:  Table [dbo].[TransactionServices]    Script Date: 07/22/2016 11:10:20 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[BUYSELLTRANSACTIONDETAILS](
	[BuySellTransactionDetailID] [int] IDENTITY(1,1) NOT NULL,
	[BuySellTransactionID] [int] NULL,
	[LoaiGiaoDich] [nvarchar](10) NULL,
	[LoaiVang] [nvarchar](50) NULL,
	[GiaVang] [money] NULL,
	[CanNang] [float] NULL,
	[TienCong] [money] NULL,
	[TienBuVang] [money] NULL,
	[TongCong] [money] NULL,
 CONSTRAINT [BuySellTransactionDetailID] PRIMARY KEY CLUSTERED 
(
	[BuySellTransactionDetailID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[BUYSELLTRANSACTIONDETAILS]  WITH NOCHECK ADD  CONSTRAINT [FK_BUYSELLTRANSACTIONDETAILS_BUYSELLTRANSACTIONS] FOREIGN KEY([BuySellTransactionDetailID])
REFERENCES [dbo].[BUYSELLTRANSACTIONS] ([BuySellTransactionID])
GO

ALTER TABLE [dbo].[BUYSELLTRANSACTIONDETAILS] CHECK CONSTRAINT [FK_BUYSELLTRANSACTIONDETAILS_BUYSELLTRANSACTIONS]
GO


