USE [Cam_Do_Database]
GO

/****** Object:  Table [dbo].[TransactionServices]    Script Date: 07/22/2016 11:10:20 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[BUYSELLTRANSACTIONS](
	[BuySellTransactionID] [int] IDENTITY(1,1) NOT NULL,
	[CustomerSTT] [int] NULL,
	[EmployeeSTT] [int] NULL,
	[date] [date] NULL,
	[TongCong] [money] NULL,
 CONSTRAINT [BuySellTransactionID] PRIMARY KEY CLUSTERED 
(
	[BuySellTransactionID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[BUYSELLTRANSACTIONS]  WITH NOCHECK ADD  CONSTRAINT [FK_BUYSELLTRANSACTIONS_CUSTOMERS] FOREIGN KEY([CustomerSTT])
REFERENCES [dbo].[CUSTOMERS] ([STT])
GO

ALTER TABLE [dbo].[BUYSELLTRANSACTIONS] CHECK CONSTRAINT [FK_BUYSELLTRANSACTIONS_CUSTOMERS]
GO

ALTER TABLE [dbo].[BUYSELLTRANSACTIONS]  WITH NOCHECK ADD  CONSTRAINT [FK_BUYSELLTRANSACTIONS_EMPLOYEES] FOREIGN KEY([EmployeeSTT])
REFERENCES [dbo].[EMPLOYEES] ([STT])
GO

ALTER TABLE [dbo].[BUYSELLTRANSACTIONS] CHECK CONSTRAINT [FK_BUYSELLTRANSACTIONS_EMPLOYEES]
GO

